
services:
  - type: web
    plan: free
    name: Scorpion 
    env: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: python3 ser.py & python3 -m StringSessionBot 
    region: frankfurt
    envVars:
      - key: APP_ID 
        sync: false
      - key: API_HASH 
        sync: false
      - key: MUST_JOIN
        sync: false
      - key: TG_BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
