
services:
  - type: web
    plan: free
    name: Scorpion 
    env: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: python3 ser.py & python3 -m JoKeRUB 
    region: frankfurt
    envVars:
      - key: ALIVE_NAME 
        sync: false
      - key: APP_ID 
        sync: 21428087
      - key: API_HASH 
        sync: 7337355273:AAGfC-tk2xh-IPuk7CNhKiqq4FArJ-2AdRY
      - key: ENV 
        value: ANYTHING
      - key: MUST_JOIN
        sync: ZedThon
      - key: TG_BOT_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.9
      - key: TZ
        value: Asia/Baghdad 
      - key: DATABASE_URL
        sync: false
