
services:
  - type: web
    plan: free
    name: Scor
    env: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: python3 ser.py & python3 -m generator.py 
    region: frankfurt
    envVars:
      - key: APP_ID 
        sync: false
      - key: API_HASH 
        sync: false
      - key: TG_BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
